/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "common": {
            "invalidToken": string;
            "expiredToken": string;
            "wrongOldPassword": string;
        };
        "customer": {
            "customerNotFound": string;
            "invalidPassword": string;
            "invalidEmail": string;
            "customerExits": string;
        };
    };
    "common": {
        "word": {
            "notFound": string;
            "file": string;
            "user": string;
            "password": string;
            "invalid": string;
            "token": string;
            "notification": string;
            "post": string;
            "favoritePost": string;
            "commentPost": string;
        };
        "exc": {
            "badRequest": string;
            "notFound": string;
            "internalServerError": string;
            "forbidden": string;
            "unauthorized": string;
            "conflict": string;
            "expectationFailed": string;
            "serviceUnavailable": string;
        };
        "validationError": {
            "date": string;
        };
    };
    "post": {
        "imagesInvalid": string;
        "postNotFound": string;
    };
    "test": {
        "params": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
